Repository NYPL/nypl-library-card-app, pull requests merged in 2022-10, with the labels that each got.

#158 Reno 3107: Add Translations For Instuctions
  public/locales/ar/common.json
  public/locales/bn/common.json
  public/locales/en/common.json
  public/locales/fr/common.json
  public/locales/ht/common.json
  public/locales/ko/common.json
  public/locales/pl/common.json
  public/locales/ru/common.json
  public/locales/ur/common.json
  public/locales/zhcn/common.json
  src/data/languages.ts
Labels: ship it

#157 RENO-3104: Language menu
  pages/new/index.tsx
  public/locales/ar/common.json
  public/locales/bn/common.json
  public/locales/en/common.json
  public/locales/fr/common.json
  public/locales/ht/common.json
  public/locales/ko/common.json
  public/locales/pl/common.json
  public/locales/ru/common.json
  public/locales/ur/common.json
  public/locales/zhcn/common.json
  src/components/LanguageMenu/LanguageMenu.test.tsx
  src/components/LanguageMenu/LanguageMenu.tsx
  src/data/languages.ts
Labels: ship it

#159 RENO-3109: Translated form fields
  pages/account/index.tsx
  pages/location/index.tsx
  pages/personal/index.tsx
  pages/review/index.tsx
  pages/workAddress/index.tsx
  public/locales/ar/common.json
  public/locales/bn/common.json
  public/locales/en/common.json
  public/locales/es/common.json
  public/locales/fr/common.json
  public/locales/ht/common.json
  public/locales/ko/common.json
  public/locales/pl/common.json
  public/locales/ru/common.json
  public/locales/ur/common.json
  src/components/AcceptTermsFormFields/AcceptTermsFormFields.test.tsx
  src/components/AcceptTermsFormFields/index.tsx
  src/components/AccountFormFields/AccountFormFields.test.tsx
  src/components/AccountFormFields/index.tsx
  src/components/AddressFormFields/AddressFormFields.test.tsx
  src/components/AddressFormFields/index.tsx
  src/components/AgeFormFields/AgeFormFields.test.tsx
  src/components/AgeFormFields/index.tsx
  src/components/LanguageMenu/LanguageMenu.test.tsx
  src/components/LibraryListFormFields/LibraryListFormFields.test.tsx
  src/components/LibraryListFormFields/index.tsx
  src/components/PersonalFormFields/PersonalFormFields.test.tsx
  src/components/PersonalFormFields/index.tsx
  src/components/ReviewFormContainer/index.tsx
  src/components/UsernameValidationFormFields/UsernameValidationFormFields.test.tsx
  src/components/UsernameValidationFormFields/index.tsx
  testHelper/utils.tsx
Labels: ship it

#161 RENO-3108: Add Translations For Address And Account Page
  pages/new/index.tsx
  public/locales/ar/common.json
  public/locales/bn/common.json
  public/locales/en/common.json
  public/locales/es/common.json
  public/locales/fr/common.json
  public/locales/ru/common.json
  public/locales/zhcn/common.json
  src/components/AcceptTermsFormFields/index.tsx
  src/components/AccountFormFields/index.tsx
  src/components/AddressFormFields/index.tsx
  src/components/PersonalFormFields/index.tsx
  src/components/ReviewFormContainer/index.tsx
  src/components/UsernameValidationFormFields/index.tsx
Labels: ship it

#160 RENO-3106: Home Library translations
  __tests__/library-card_review.test.tsx
  src/components/AccountFormContainer/index.tsx
  src/components/AccountFormFields/AccountFormFields.test.tsx
  src/components/AccountFormFields/index.tsx
  src/components/LibraryListFormFields/LibraryListFormFields.test.tsx
  src/components/LibraryListFormFields/index.tsx
  src/components/ReviewFormContainer/index.tsx
  src/data/ilsLibraryList.ts
  src/data/libraryNamesAr.ts
  src/data/libraryNamesBn.ts
  src/data/libraryNamesEn.ts
  src/data/libraryNamesEs.ts
  src/data/libraryNamesFr.ts
  src/data/libraryNamesHt.ts
  src/data/libraryNamesKo.ts
  src/data/libraryNamesPl.ts
  src/data/libraryNamesRu.ts
  src/data/libraryNamesUr.ts
  src/data/libraryNamesZhcn.ts
  src/utils/formDataUtils.ts
Labels: ship it

#162 RENO-3203: Add "dir" and "lang" Attribute Support
  next-i18next.config.js
  pages/_app.tsx
  pages/_document.tsx
  src/components/ApplicationContainer/index.tsx
  src/components/LanguageMenu/LanguageMenu.tsx
Labels: Needs Review

#163 RENO-3110: Error Translations
  pages/_app.tsx
  pages/address-verification/index.tsx
  pages/congrats/index.tsx
  public/locales/en/common.json
  public/locales/es/common.json
  src/components/AcceptTermsFormFields/AcceptTermsFormFields.test.tsx
  src/components/AcceptTermsFormFields/index.tsx
  src/components/AccountFormContainer/index.tsx
  src/components/AccountFormFields/AccountFormFields.test.tsx
  src/components/AccountFormFields/index.tsx
  src/components/AddressContainer/index.tsx
  src/components/AddressFormFields/AddressFormFields.test.tsx
  src/components/AddressFormFields/index.tsx
  src/components/AddressVerificationContainer/index.tsx
  src/components/AgeFormFields/AgeFormFields.test.tsx
  src/components/AgeFormFields/index.tsx
  src/components/ApiErrors/ApiErrors.test.tsx
  src/components/ApiErrors/index.tsx
  src/components/ApplicationContainer/index.tsx
  src/components/LanguageMenu/LanguageMenu.test.tsx
  src/components/LibraryListFormFields/LibraryListFormFields.test.tsx
  src/components/PersonalFormContainer/index.tsx
  src/components/PersonalFormFields/PersonalFormFields.test.tsx
  src/components/PersonalFormFields/index.tsx
  src/components/ReviewFormContainer/index.tsx
  src/components/UsernameValidationFormFields/UsernameValidationFormFields.test.tsx
  src/components/UsernameValidationFormFields/index.tsx
  src/components/WorkAddressContainer/index.tsx
  src/data/apiErrorMessageTranslations.ts
  src/data/apiMessageTranslations.ts
  src/utils/__tests__/renderErrorsUtils.test.tsx
  src/utils/api.ts
  src/utils/formDataUtils.ts
  src/utils/renderErrorsUtils.tsx
  src/utils/utils.ts
Labels: ship it

#164 RENO-3111/add international instructions
  __tests__/library-card_address-verification.test.tsx
  __tests__/library-card_review.test.tsx
  pages/_app.tsx
  pages/_document.tsx
  pages/account/index.tsx
  pages/address-verification/index.tsx
  pages/congrats/index.tsx
  pages/location/index.tsx
  pages/new/index.tsx
  pages/personal/index.tsx
  pages/review/index.tsx
  pages/workAddress/index.tsx
  public/locales/ar/common.json
  public/locales/bn/common.json
  public/locales/en/common.json
  public/locales/es/common.json
  public/locales/fr/common.json
  public/locales/ht/common.json
  public/locales/ko/common.json
  public/locales/pl/common.json
  public/locales/ru/common.json
  public/locales/ur/common.json
  public/locales/zhcn/common.json
  src/components/AcceptTermsFormFields/AcceptTermsFormFields.test.tsx
  src/components/AcceptTermsFormFields/index.tsx
  src/components/AccountFormFields/AccountFormFields.test.tsx
  src/components/AddressContainer/AddressContainer.test.tsx
  src/components/AddressContainer/index.tsx
  src/components/AddressFormFields/AddressFormFields.test.tsx
  src/components/AddressFormFields/index.tsx
  src/components/AddressVerificationContainer/index.tsx
  src/components/AgeFormFields/AgeFormFields.test.tsx
  src/components/AgeFormFields/index.tsx
  src/components/ConfirmationGraphic/ConfirmationGraphic.test.tsx
  src/components/ConfirmationGraphic/index.tsx
  src/components/LibraryListFormFields/LibraryListFormFields.test.tsx
  src/components/LibraryListFormFields/index.tsx
  src/components/PersonalFormFields/PersonalFormFields.test.tsx
  src/components/ReviewFormContainer/index.tsx
  src/components/RoutingLinks.tsx/RoutingLinks.module.css
  src/components/UsernameValidationFormFields/index.tsx
  src/components/WorkAddressContainer/index.tsx
Labels: ship it

#165 RENO-3179: Passing the selected preferred language to Patron API
  src/components/PersonalFormContainer/index.tsx
  src/interfaces.ts
  src/utils/__tests__/api.test.ts
  src/utils/formDataUtils.ts
Labels: ship it

#166 Reno 3220/Add Missing Translations
  public/locales/ht/common.json
  public/locales/ko/common.json
  public/locales/pl/common.json
  public/locales/ur/common.json
Labels: ship it

#168 Removes the translated library names
  __tests__/library-card_review.test.tsx
  src/components/AccountFormContainer/index.tsx
  src/components/AccountFormFields/index.tsx
  src/components/LibraryListFormFields/LibraryListFormFields.test.tsx
  src/components/LibraryListFormFields/index.tsx
  src/components/ReviewFormContainer/index.tsx
  src/data/ilsLibraryList.ts
  src/data/libraryNamesAr.ts
  src/data/libraryNamesBn.ts
  src/data/libraryNamesEn.ts
  src/data/libraryNamesEs.ts
  src/data/libraryNamesFr.ts
  src/data/libraryNamesHt.ts
  src/data/libraryNamesKo.ts
  src/data/libraryNamesPl.ts
  src/data/libraryNamesRu.ts
  src/data/libraryNamesUr.ts
  src/data/libraryNamesZhcn.ts
  src/utils/formDataUtils.ts
Labels: ship it

#169 Reno-3222/ Add international instructions
  public/locales/ar/common.json
  public/locales/bn/common.json
  public/locales/en/common.json
  public/locales/es/common.json
  public/locales/fr/common.json
  public/locales/ht/common.json
  public/locales/ko/common.json
  public/locales/pl/common.json
  public/locales/ru/common.json
  public/locales/ur/common.json
  public/locales/zhcn/common.json
  src/components/AddressContainer/AddressContainer.test.tsx
  src/components/AddressContainer/index.tsx
  src/components/AgeFormFields/AgeFormFields.test.tsx
  src/components/AgeFormFields/index.tsx
  src/components/PersonalFormFields/PersonalFormFields.test.tsx
  src/components/PersonalFormFields/index.tsx
Labels: Ship It

#167 RENO-3221: Additional error messages
  public/locales/ar/common.json
  public/locales/bn/common.json
  public/locales/es/common.json
  public/locales/fr/common.json
  public/locales/ht/common.json
  public/locales/ko/common.json
  public/locales/pl/common.json
  public/locales/ru/common.json
  public/locales/ur/common.json
  public/locales/zhcn/common.json
  src/data/apiErrorMessageTranslations.ts
Labels: Ship It

#170 moving the language menu up on the page
  pages/new/index.tsx
  src/components/RoutingLinks.tsx/RoutingLinks.module.css
  src/styles/components/globals.scss
Labels: Ship It

#174 RENO-3225: Add Congrats Page Translations And Aria-labels
  public/locales/ar/common.json
  public/locales/bn/common.json
  public/locales/es/common.json
  public/locales/fr/common.json
  public/locales/ht/common.json
  public/locales/ko/common.json
  public/locales/pl/common.json
  public/locales/ru/common.json
  public/locales/ur/common.json
  public/locales/zhcn/common.json
Labels: Ship It

#176 Add last missing translations
  public/locales/ar/common.json
  public/locales/bn/common.json
  public/locales/es/common.json
  public/locales/fr/common.json
  public/locales/ht/common.json
  public/locales/ko/common.json
  public/locales/pl/common.json
  public/locales/ru/common.json
  public/locales/ur/common.json
  public/locales/zhcn/common.json
Labels: Ship It

#175 RENO-3215: Add requiredLabelText Prop For Required Text
  package-lock.json
  package.json
  src/components/FormField/index.tsx
Labels: Ship It

#173 Refactoring and alphabetically ordering some values.
  __tests__/library-card_address-verification.test.tsx
  __tests__/library-card_review.test.tsx
  pages/congrats/index.tsx
  public/locales/en/common.json
  src/components/AcceptTermsFormFields/AcceptTermsFormFields.test.tsx
  src/components/AccountFormFields/AccountFormFields.test.tsx
  src/components/AddressContainer/AddressContainer.test.tsx
  src/components/AddressContainer/index.tsx
  src/components/AddressFormFields/AddressFormFields.test.tsx
  src/components/AgeFormFields/AgeFormFields.test.tsx
  src/components/AgeFormFields/index.tsx
  src/components/ApiErrors/ApiErrors.test.tsx
  src/components/ConfirmationGraphic/ConfirmationGraphic.test.tsx
  src/components/LibraryListFormFields/LibraryListFormFields.test.tsx
  src/components/PersonalFormFields/PersonalFormFields.test.tsx
  src/components/ReviewFormContainer/index.tsx
  src/components/UsernameValidationFormFields/UsernameValidationFormFields.test.tsx
  src/components/UsernameValidationFormFields/index.tsx
  src/components/WorkAddressContainer/index.tsx
  src/data/apiErrorMessageTranslations.ts
  src/data/apiMessageTranslations.ts
  testHelper/utils.tsx
Labels: Ship It

#177 RENO-3227: Adding IP-based user location Google translations
  __tests__/library-card_review.test.tsx
  src/components/ReviewFormContainer/index.tsx
  src/data/ipLocationMessageTranslations.ts
  src/utils/formDataUtils.ts
Labels: Ship It

#178 Reno 3229: Update Arabic Translation
  public/locales/ar/common.json
Labels: Ship It

#181 RENO-3235: Second Revision Changes Pt 1
  public/locales/ar/common.json
  public/locales/ko/common.json
  public/locales/pl/common.json
Labels: Ship It

#182 RENO-3236: Section Revision Pt 2
  public/locales/fr/common.json
  public/locales/ru/common.json
Labels: Ship It
